/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Asus
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Hopital = new javax.swing.JButton();
        service = new javax.swing.JButton();
        docteur = new javax.swing.JButton();
        Infirmier = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        personnel = new javax.swing.JButton();
        patientHos = new javax.swing.JButton();
        salle = new javax.swing.JButton();
        patient = new javax.swing.JButton();
        acte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniProjet BD Marwen AOUITI");

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        Hopital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hospital (2).png"))); // NOI18N
        Hopital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HopitalActionPerformed(evt);
            }
        });
        jPanel1.add(Hopital);

        service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/service.png"))); // NOI18N
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        jPanel1.add(service);

        docteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor.png"))); // NOI18N
        docteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docteurActionPerformed(evt);
            }
        });
        jPanel1.add(docteur);

        Infirmier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nurse.png"))); // NOI18N
        Infirmier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfirmierActionPerformed(evt);
            }
        });
        jPanel1.add(Infirmier);

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boss.png"))); // NOI18N
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin);

        personnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/staff.png"))); // NOI18N
        personnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personnelActionPerformed(evt);
            }
        });
        jPanel1.add(personnel);

        patientHos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        patientHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHosActionPerformed(evt);
            }
        });
        jPanel1.add(patientHos);

        salle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medical-room.png"))); // NOI18N
        salle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salleActionPerformed(evt);
            }
        });
        jPanel1.add(salle);

        patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor (1).png"))); // NOI18N
        patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientActionPerformed(evt);
            }
        });
        jPanel1.add(patient);

        acte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice.png"))); // NOI18N
        acte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acteActionPerformed(evt);
            }
        });
        jPanel1.add(acte);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HopitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HopitalActionPerformed
        AddHospital h = new AddHospital();
        h.show();
    }//GEN-LAST:event_HopitalActionPerformed

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        AddService s = new AddService();
        s.show();
    }//GEN-LAST:event_serviceActionPerformed

    private void docteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docteurActionPerformed
        addDoctor d = new addDoctor();
        d.show();
    }//GEN-LAST:event_docteurActionPerformed

    private void InfirmierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfirmierActionPerformed
        addInfirmier i = new addInfirmier();
        i.show();
    }//GEN-LAST:event_InfirmierActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        adminUI a = new adminUI();
        a.show();
    }//GEN-LAST:event_adminActionPerformed

    private void personnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personnelActionPerformed
        Personnel p = new Personnel();
        p.show();
    }//GEN-LAST:event_personnelActionPerformed

    private void patientHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHosActionPerformed
        PatientMalade pm = new PatientMalade();
        pm.show();
    }//GEN-LAST:event_patientHosActionPerformed

    private void patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientActionPerformed
        PatientUI pt = new PatientUI();
        pt.show();
    }//GEN-LAST:event_patientActionPerformed

    private void salleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salleActionPerformed
        Salle s = new Salle();
        s.show();
    }//GEN-LAST:event_salleActionPerformed

    private void acteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acteActionPerformed
        ActeUI a = new ActeUI();
        a.show();
    }//GEN-LAST:event_acteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hopital;
    private javax.swing.JButton Infirmier;
    private javax.swing.JButton acte;
    private javax.swing.JButton admin;
    private javax.swing.JButton docteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton patient;
    private javax.swing.JButton patientHos;
    private javax.swing.JButton personnel;
    private javax.swing.JButton salle;
    private javax.swing.JButton service;
    // End of variables declaration//GEN-END:variables
}
