/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import daoPattern.Patient;

/**
 *
 * @author Asus
 */
public class PatientUI extends javax.swing.JFrame {

    /**
     * Creates new form PatientUI
     */
    public PatientUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numDossier = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Hop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        service = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addresse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        montant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mutuelle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maladie = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des patients");

        jPanel1.setLayout(new java.awt.GridLayout(9, 9));

        jLabel1.setText("N° Dossier (En cas de suppression)");
        jPanel1.add(jLabel1);
        jPanel1.add(numDossier);

        jLabel2.setText("N° Hopital");
        jPanel1.add(jLabel2);
        jPanel1.add(Hop);

        jLabel3.setText("N° Service");
        jPanel1.add(jLabel3);
        jPanel1.add(service);

        jLabel4.setText("Nom");
        jPanel1.add(jLabel4);
        jPanel1.add(nom);

        jLabel9.setText("Addresse");
        jPanel1.add(jLabel9);
        jPanel1.add(addresse);

        jLabel6.setText("Téléphone");
        jPanel1.add(jLabel6);
        jPanel1.add(telephone);

        jLabel7.setText("Montant payé");
        jPanel1.add(jLabel7);
        jPanel1.add(montant);

        jLabel8.setText("N° Mutuelle");
        jPanel1.add(jLabel8);
        jPanel1.add(mutuelle);

        jLabel5.setText("Description Maladie");
        jPanel1.add(jLabel5);
        jPanel1.add(maladie);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gestion des Patients");

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel2.add(ajouter);

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        jPanel2.add(supprimer);

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel2.add(annuler);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        Patient p = new Patient(Integer.parseInt(Hop.getText()),
                                Integer.parseInt(service.getText()),
                                nom.getText(),
                                addresse.getText(),
                                telephone.getText(),
                                Integer.parseInt(montant.getText()),
                                Integer.parseInt(mutuelle.getText()),
                                maladie.getText());
        p.updatePatient();
    }//GEN-LAST:event_ajouterActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        Patient p = new Patient(Integer.parseInt(numDossier.getText()),
                                Integer.parseInt(Hop.getText()),
                                Integer.parseInt(service.getText()),
                                nom.getText(),
                                addresse.getText(),
                                telephone.getText(),
                                Integer.parseInt(montant.getText()),
                                Integer.parseInt(mutuelle.getText()),
                                maladie.getText());
        p.deletePatient();
    }//GEN-LAST:event_supprimerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        numDossier.setText("");
        Hop.setText("");
        service.setText("");
        nom.setText("");
        addresse.setText("");
        telephone.setText("");
        montant.setText("");
        mutuelle.setText("");
        maladie.setText("");
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hop;
    private javax.swing.JTextField addresse;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField maladie;
    private javax.swing.JTextField montant;
    private javax.swing.JTextField mutuelle;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numDossier;
    private javax.swing.JTextField service;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
