/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import daoPattern.PersonnelData;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objects.PersonnelDao;

/**
 *
 * @author Asus
 */
public class Personnel extends javax.swing.JFrame {

    /**
     * Creates new form Personnel
     */
    public Personnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        numSrv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numHop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomPerso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addrPerso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telPerso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        salPerso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateEmbPerso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        spprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 7));

        jLabel4.setText("N° Service");
        jPanel1.add(jLabel4);

        numSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSrvActionPerformed(evt);
            }
        });
        jPanel1.add(numSrv);

        jLabel5.setText("N° Hopital");
        jPanel1.add(jLabel5);
        jPanel1.add(numHop);

        jLabel3.setText("Nom");
        jPanel1.add(jLabel3);
        jPanel1.add(nomPerso);

        jLabel6.setText("Addresse");
        jPanel1.add(jLabel6);
        jPanel1.add(addrPerso);

        jLabel7.setText("Téléphone");
        jPanel1.add(jLabel7);

        telPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telPersoActionPerformed(evt);
            }
        });
        jPanel1.add(telPerso);

        jLabel8.setText("Salaire");
        jPanel1.add(jLabel8);
        jPanel1.add(salPerso);

        jLabel1.setText("Date embauche");
        jPanel1.add(jLabel1);

        dateEmbPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateEmbPersoActionPerformed(evt);
            }
        });
        jPanel1.add(dateEmbPerso);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion des Personnels");

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel2.add(ajouter);

        spprimer.setText("Supprimer");
        spprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spprimerActionPerformed(evt);
            }
        });
        jPanel2.add(spprimer);

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel2.add(annuler);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSrvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numSrvActionPerformed

    private void telPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telPersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telPersoActionPerformed

    private void dateEmbPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateEmbPersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateEmbPersoActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
         PersonnelData p = new PersonnelData(Integer.parseInt(numSrv.getText()),
                                             Integer.parseInt(numHop.getText()),
                                             Integer.parseInt(salPerso.getText()),
                                             nomPerso.getText(),
                                             addrPerso.getText(),
                                             telPerso.getText(),
                                             dateEmbPerso.getText());
        PersonnelDao add = new PersonnelDao();
        add.updatePersonnel(p);
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
        JOptionPane.showMessageDialog(frame,"Record was inserted sucessfully");
    }//GEN-LAST:event_ajouterActionPerformed

    private void spprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spprimerActionPerformed
         PersonnelData p = new PersonnelData(Integer.parseInt(numHop.getText()),nomPerso.getText());
        
        PersonnelDao supp = new PersonnelDao();
        supp.deletePersonnel(p);
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
        JOptionPane.showMessageDialog(frame,"Record was deleted sucessfully");
    }//GEN-LAST:event_spprimerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        numHop.setText("");
        numSrv.setText("");
        nomPerso.setText("");
        nomPerso.setText("");
        addrPerso.setText("");
        telPerso.setText("");
        salPerso.setText("");
        dateEmbPerso.setText("");
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personnel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrPerso;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField dateEmbPerso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomPerso;
    private javax.swing.JTextField numHop;
    private javax.swing.JTextField numSrv;
    private javax.swing.JTextField salPerso;
    private javax.swing.JButton spprimer;
    private javax.swing.JTextField telPerso;
    // End of variables declaration//GEN-END:variables
}
