/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import daoPattern.SalleData;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objects.SalleDaoImpl;

/**
 *
 * @author Asus
 */
public class Salle extends javax.swing.JFrame {

    /**
     * Creates new form Salle
     */
    public Salle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numSrv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numHop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numInf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nbLits = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des Salles");

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        jLabel3.setText("N° Service");
        jPanel1.add(jLabel3);

        numSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSrvActionPerformed(evt);
            }
        });
        jPanel1.add(numSrv);

        jLabel4.setText("N° Hopital");
        jPanel1.add(jLabel4);
        jPanel1.add(numHop);

        jLabel5.setText("N° Surveillant");
        jPanel1.add(jLabel5);

        numInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numInfActionPerformed(evt);
            }
        });
        jPanel1.add(numInf);

        jLabel1.setText("Nombre des Lits");
        jPanel1.add(jLabel1);
        jPanel1.add(nbLits);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel2.add(ajouter);

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        jPanel2.add(supprimer);

        annuler.setText("Annuler");
        jPanel2.add(annuler);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion des Salles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSrvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numSrvActionPerformed

    private void numInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numInfActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        SalleData s = new SalleData(Integer.parseInt(numSrv.getText()),
                                    Integer.parseInt(numHop.getText()),
                                    Integer.parseInt(numInf.getText()),
                                    Integer.parseInt(nbLits.getText()));
        SalleDaoImpl supp = new SalleDaoImpl();
        supp.deleteSalle(s);
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
        JOptionPane.showMessageDialog(frame,"Record was Deleted sucessfully");
    }//GEN-LAST:event_supprimerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        SalleData s = new SalleData(Integer.parseInt(numSrv.getText()),
                                    Integer.parseInt(numHop.getText()),
                                    Integer.parseInt(numInf.getText()),
                                    Integer.parseInt(nbLits.getText()));
        SalleDaoImpl add = new SalleDaoImpl();
        add.updateSalle(s);
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
        JOptionPane.showMessageDialog(frame,"Record was inserted sucessfully");
    }//GEN-LAST:event_ajouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nbLits;
    private javax.swing.JTextField numHop;
    private javax.swing.JTextField numInf;
    private javax.swing.JTextField numSrv;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
